-- 全部为虚构版权数据，仅用于授权判定演示，不对应任何真实节目或真实播放。
CREATE TABLE program (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(40)  NOT NULL UNIQUE,
    title       VARCHAR(200) NOT NULL,
    CONSTRAINT pk_program PRIMARY KEY (id)
);

CREATE TABLE contract (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    program_id      BIGINT       NOT NULL REFERENCES program(id),
    contract_no     VARCHAR(40)  NOT NULL UNIQUE,
    licensee        VARCHAR(120) NOT NULL,          -- 被授权方/渠道方
    region_code     VARCHAR(20)  NOT NULL,          -- 地区，如 CN-HK / SG
    channel_code    VARCHAR(40)  NOT NULL,          -- 渠道，如 WEB / MOBILE / OTT
    start_at        TIMESTAMP     NOT NULL,         -- UTC，含该时刻
    end_at          TIMESTAMP,                      -- UTC，不含该时刻；NULL 表示开放结尾
    exclusive       BOOLEAN       NOT NULL DEFAULT FALSE,
    note            VARCHAR(300),
    CONSTRAINT pk_contract PRIMARY KEY (id),
    CONSTRAINT chk_time_range CHECK (end_at IS NULL OR end_at > start_at)
);

-- 排他约定：exclusive=TRUE 的合同在此登记；判定时同地区同渠道、
-- 被其他权利方持有的有效授权会与之冲突。
CREATE TABLE exclusivity_agreement (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contract_id  BIGINT      NOT NULL UNIQUE REFERENCES contract(id),
    region_code  VARCHAR(20) NOT NULL,
    channel_code VARCHAR(40) NOT NULL,
    start_at     TIMESTAMP   NOT NULL,
    end_at       TIMESTAMP,
    note         VARCHAR(300)
);

CREATE TABLE contract_language (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    contract_id  BIGINT      NOT NULL REFERENCES contract(id),
    language_code VARCHAR(20) NOT NULL,             -- 语言版本，如 zh-Hans / zh-Hant / en
    UNIQUE (contract_id, language_code)
);

CREATE INDEX idx_contract_lookup
    ON contract (program_id, region_code, channel_code, start_at, end_at);
